### ISSUE TITLE
CLI tool is not working

### ISSUE THREAD

**Issue by deiga** [getinsomnia/importers#7]
I get this error when running the CLI tool
```
$ insomnia-import
Error: Cannot find module './importers'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/.nvm/versions/node/v7.7.2/lib/node_modules/insomnia-importers/src/cli.js:5:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by gschier** [comment]
Sorry of the delay @deiga. This is indeed a bug. I haven't been using the CLI, so didn't notice. Will fix this asap. 😄

**Comment by deiga** [comment]
@gschier Figured I'd spare you the trouble and fix it myself ;)

**Comment by gschier** [comment]
Thank you @deiga!
